DO
$$
    BEGIN
        BEGIN
            ALTER TABLE vacancies
                DROP COLUMN employment_type;
            ALTER TABLE vacancies
                DROP COLUMN is_open;
            ALTER TABLE vacancies
                DROP COLUMN IF EXISTS salary_range;
            ALTER TABLE vacancies
                DROP COLUMN IF EXISTS image_url;
            ALTER TABLE vacancies
                DROP COLUMN IF EXISTS id CASCADE;
        EXCEPTION
            WHEN others THEN
        END;
    END
$$;

DELETE
FROM vacancies;
ALTER TABLE vacancies
    ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid();

ALTER TABLE vacancies
    ADD COLUMN IF NOT EXISTS image_id                       VARCHAR(255),
    ADD COLUMN IF NOT EXISTS description                    TEXT,
    ADD COLUMN IF NOT EXISTS work_arrangement               VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS department                     VARCHAR(50) NOT NULL,
    ADD COLUMN IF NOT EXISTS location_type                  VARCHAR(50),
    ADD COLUMN IF NOT EXISTS status                         VARCHAR(50),
    ADD COLUMN IF NOT EXISTS created_at                     TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS updated_at                     TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS due_date                       DATE,
    ADD COLUMN IF NOT EXISTS specialization                 VARCHAR(255),
    ADD COLUMN IF NOT EXISTS experience_level               VARCHAR(50),
    ADD COLUMN IF NOT EXISTS need_relocation                BOOLEAN,
    ADD COLUMN IF NOT EXISTS linkedin_post_link             VARCHAR(255),
    ADD COLUMN IF NOT EXISTS x_post_link                    VARCHAR(255),
    ADD COLUMN IF NOT EXISTS needs_quiz                     BOOLEAN,
    ADD COLUMN IF NOT EXISTS needs_citizenship_verification BOOLEAN,
    ADD COLUMN IF NOT EXISTS views                          INTEGER,
    ADD COLUMN IF NOT EXISTS applications                   INTEGER,
    ADD COLUMN IF NOT EXISTS currency                       VARCHAR(50),
    ADD COLUMN IF NOT EXISTS time_period                    VARCHAR(50),
    ADD COLUMN IF NOT EXISTS lower_bound                    INTEGER,
    ADD COLUMN IF NOT EXISTS upper_bound                    INTEGER;

CREATE TABLE IF NOT EXISTS vacancy_locations
(
    vacancy_id UUID         NOT NULL,
    city       VARCHAR(255) NOT NULL,
    country    VARCHAR(255) NOT NULL,
    PRIMARY KEY (vacancy_id, city),
    FOREIGN KEY (vacancy_id) REFERENCES vacancies (id)
);

CREATE TABLE IF NOT EXISTS vacancy_languages
(
    vacancy_id UUID REFERENCES vacancies (id),
    language   varchar(255),
    level      varchar(255)
);

create table if not exists interviews
(
    id         bigint generated by default as identity primary key,
    date_time  timestamptz,
    vacancy_id uuid,
    user_id    bigint,
    is_deleted boolean DEFAULT false,
    foreign key (vacancy_id) references vacancies (id),
    foreign key (user_id) references users (id)
);

ALTER TABLE users_vacancies
    DROP COLUMN IF EXISTS vacancy_id CASCADE;

ALTER TABLE users_vacancies
    ADD COLUMN vacancy_id UUID references vacancies (id);

