create table if not exists interviews
(
    id         bigint generated by default as identity primary key,
    date_time  timestamptz,
    vacancy_id uuid,
    user_id    bigint,
    is_deleted boolean DEFAULT false,
    foreign key (vacancy_id) references vacancies (id),
    foreign key (user_id) references users (id)
);
