create table IF NOT EXISTS quizzes
(
    id              bigint generated by default as identity,
    create_strategy varchar not null,
    description     varchar,
    primary key (id)
);


create table IF NOT EXISTS leaves
(
    id            bigint generated by default as identity,
    name          varchar   not null unique,
    creation_time timestamp not null,
    is_available  boolean   not null,
    primary key (id)

);
create table questions
(
    id               uuid,
    time_for_reading integer   not null,
    difficulty_level integer   not null,
    type             varchar   not null,
    content          varchar   not null,
    description      varchar   not null,
    creation_time    timestamp not null,
    update_time      timestamp,
    is_available     boolean   not null,
--   author_id        integer   not null references users (user_id),
    primary key (id)

);
create table IF NOT EXISTS quiz_leaves
(
    quiz_id bigint references quizzes (id),
    leaf_id bigint references leaves (id),
    primary key (quiz_id, leaf_id)
);
create table IF NOT EXISTS question_leaves
(
    question_id uuid references questions (id),
    leaf_id     bigint references leaves (id),
    primary key (question_id, leaf_id)
);
create table IF NOT EXISTS quiz_questions
(
    quiz_id     bigint references quizzes (id),
    question_id uuid references questions (id),
    primary key (quiz_id, question_id)
);


