package ua.com.quizservice.util.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import ua.com.quizservice.config.MapperConfig;
import ua.com.quizservice.dto.question.QuestionDto;
import ua.com.quizservice.dto.quiz.QuizQuestionDto;
import ua.com.quizservice.entity.quiz.QuizQuestion;

/**
 * Mapper interface for converting between {@link QuizQuestion} entities and {@link QuizQuestionDto}
 * DTOs. Uses {@link MapperConfig} for configuration.
 *
 * <p>The methods defined in this interface provide mapping between entity and DTO representations
 * of {@link QuizQuestion} instances. Implementation is generated by MapStruct during the build
 * process.
 *
 * @see MapperConfig
 */
@Mapper(uses = QuestionDto.class, config = MapperConfig.class)
public interface QuizQuestionMapper {

  @Mapping(target = "question", source = "questionDto")
  QuizQuestion toEntity(QuizQuestionDto quizQuestionDto);

  @Mapping(target = "questionDto", source = "question")
  QuizQuestionDto toDto(QuizQuestion quizQuestion);
}
